export const FORM_SUBMITTED_REQUEST = "FORM_SUBMITTED_REQUEST";
export const FORM_SUBMITTED_SUCCESS = "FORM_SUBMITTED_SUCCESS";
export const FORM_SUBMITTED_FAIL = "FORM_SUBMITTED_FAIL";

export const FORM_DETAILS_REQUEST = "FORM_DETAILS_REQUEST";
export const FORM_DETAILS_SUCCESS = "FORM_DETAILS_SUCCESS";
export const FORM_DETAILS_FAIL = "FORM_DETAILS_FAIL";
export const FORM_DETAILS_RESET = "FORM_DETAILS_RESET";

export const FORM_LIST_REQUEST = "FORM_LIST_REQUEST";
export const FORM_LIST_SUCCESS = "FORM_LIST_SUCCESS";
export const FORM_LIST_FAIL = "FORM_LIST_FAIL";

export const FORM_LIST_MY_REQUEST = "FORM_LIST_MY_REQUEST";
export const FORM_LIST_MY_SUCCESS = "FORM_LIST_MY_SUCCESS";
export const FORM_LIST_MY_FAIL = "FORM_LIST_MY_FAIL";
export const FORM_LIST_MY_RESET = "FORM_LIST_MY_RESET";

export const FORM_DELIVER_REQUEST = "FORM_DELIVER_REQUEST";
export const FORM_DELIVER_SUCCESS = "FORM_DELIVER_SUCCESS";
export const FORM_DELIVER_FAIL = "FORM_DELIVER_FAIL";
export const FORM_DELIVER_RESET = "FORM_DELIVER_RESET";

export const FORM_DAILY_MY_REQUEST = "FORM_DAILY_MY_REQUEST";
export const FORM_DAILY_MY_SUCCESS = "FORM_DAILY_MY_SUCCESS";
export const FORM_DAILY_MY_FAIL = "FORM_DAILY_MY_FAIL";
