export const FORM_SUBMITTED_REQUEST = "FORM_SUBMITTED_REQUEST";
export const FORM_SUBMITTED_SUCCESS = "FORM_SUBMITTED_SUCCESS";
export const FORM_SUBMITTED_FAIL = "FORM_SUBMITTED_FAIL";

export const FORM_LIST_REQUEST = "FORM_LIST_REQUEST";
export const FORM_LIST_SUCCESS = "FORM_LIST_SUCCESS";
export const FORM_LIST_FAIL = "FORM_LIST_FAIL";

export const FORM_LIST_MY_REQUEST = "FORM_LIST_MY_REQUEST";
export const FORM_LIST_MY_SUCCESS = "FORM_LIST_MY_SUCCESS";
export const FORM_LIST_MY_FAIL = "FORM_LIST_MY_FAIL";
export const FORM_LIST_MY_RESET = "FORM_LIST_MY_RESET";
